config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      get :profile
      post :create_for_profile
    end
  end

  resources :team_mentors
  resources :team_members

  resources :members do
    resources :team_members
    resources :teams
  end
  resources :teams do
    resources :team_members do
      collection do
        get :new_form
      end
    end
    resources :team_mentors do
      collection do
        get :new_form
      end
    end
    resources :members
    resources :ratings, only: [:index]
    resources :mentorings
  end
  resources :mentors do
    resources :team_mentors
    resources :teams
    resources :ratings, except: :new
    resources :dashboard, only: :index
    resources :expert_sessions do
      member do
        post :book
      end
    end
  end

  resources :events do
    resources :attendances do
      member do
        post :attend
        post :decline
      end
    end
    collection do
      get :timeline
    end
  end
  resources :mentorings do
    resources :attendances do
      member do
        post :attend
        post :decline
      end
    end
    collection do
      get :timeline
    end
  end

  resources :expert_sessions do
    member do
      post :accept
      post :reject
    end
    resources :attendances
  end

  resources :attendances do
    member do
      post :attend
      post :decline
    end
  end

  resources :ratings, except: :new

  scope as: :calendar, path: 'calendar/:token' do
    controller :calendar do
      get :events
    end
  end

  root to: "users#profile"
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :team
  belongs_to :member

  validates_presence_of :team, :member

  def to_s
    "%s of %s" % [member, team]
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < CrudController
  polymorphic_belongs_to :member, :team, optional: true
  skip_before_action :verify_authenticity_token, only: :new_form

  def new_form
    @member = Member.new
  end

  def team_member_params
    permitted_params = params.require(:team_member)

    permitted_params.permit([
      :team_id,
      :member_id,
      :active
    ])
  end
end

app/views/team_members/_form.html.haml
= simple_form_for [parent, resource] do |f|
  - if defined?(parent.id) && resource.team_id == parent.id
    = hidden_field_tag :team, resource.team_id
  - else
    .row= f.association :team
  .row= f.association :member
  = link_to 'create new member', new_form_team_team_members_path, remote: true

  .row= f.input :active

  = f.button :submit

app/views/team_members/create.js.erb
<%= render 'create' %>

<%- unless resource.errors.present? %>
  $('.collection.members').html('<%=j render "list", resource_class: Member, collection: resource.team.members %>')
  $('.collection.teams').html('<%=j render "list", resource_class: Team, collection: resource.member.team %>')

  init();
<%- end %>

app/views/team_members/new_form.js.erb
$('.modal-content').html('<%=j render 'members/form', resource: @member, team_id: params[:team_id] %>');
init();