config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      get :profile
      post :create_for_profile
    end
  end

  resources :team_mentors
  resources :team_members

  resources :members do
    resources :team_members
    resources :teams
  end
  resources :teams do
    resources :team_members do
      collection do
        get :new_form
      end
    end
    resources :team_mentors do
      collection do
        get :new_form
      end
    end
    resources :members
    resources :ratings, only: [:index]
    resources :mentorings
  end
  resources :mentors do
    resources :team_mentors
    resources :teams
    resources :ratings, except: :new
    resources :dashboard, only: :index
    resources :expert_sessions do
      member do
        post :book
      end
    end
  end

  resources :events do
    resources :attendances do
      member do
        post :attend
        post :decline
      end
    end
    collection do
      get :timeline
    end
  end
  resources :mentorings do
    resources :attendances do
      member do
        post :attend
        post :decline
      end
    end
    collection do
      get :timeline
    end
  end

  resources :expert_sessions do
    member do
      post :accept
      post :reject
    end
    resources :attendances
  end

  resources :attendances do
    member do
      post :attend
      post :decline
    end
  end

  resources :ratings, except: :new

  scope as: :calendar, path: 'calendar/:token' do
    controller :calendar do
      get :events
    end
  end

  root to: "users#profile"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :profile, polymorphic: true, optional: true

  def self.find_by_calendar_token!(token)
    id = token[40..-1].to_i
    user = User.find(id)
    if user.calendar_token == token
      user
    else
      raise ActiveRecord::RecordNotFound
    end
  end

  def member?
    'Member' == self.profile_type
  end

  def mentor?
    'Mentor' == self.profile_type
  end

  def team?
    'Team' == self.profile_type
  end

  def to_s
    self.email
  end

  def calendar_token
    "#{Digest::SHA1.hexdigest "#{id}:#{encrypted_password}"}#{id}"
  end
end

app/controllers/users_controller.rb
class UsersController < CrudController
  has_scope :per, default: 10000, only: [ :index ]

  def profile
    if current_user.profile
      redirect_to current_user.profile
    else
      redirect_to current_user
    end
  end

  def index
    @mentors_with_no_user = Mentor.with_no_user
    @members_with_no_user = Member.with_no_user
    @unconfirmed = collection.where(sign_in_count: 0)
    @all = collection
  end

  def update
    # Don't try to update password if not provided
    if user_params[:password].blank?
      [:password, :password_confirmation].collect{|p| user_params.delete(p) }
    end

    # Special case if user can manage other users
    successfully_updated = if can? :manage, @user
      user_params.delete(:current_password)
      @user.update_attributes(user_params)
    else
      @user.update_with_password(user_params)
    end

    if successfully_updated
      # Sign in the user bypassing validation in case his password changed
      if current_user == @user
        bypass_sign_in(@user)
      end
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def create_for_profile
    @user = User.new(user_params)
    @user.email = @user.profile.email if @user.email.blank?
    @user.password = Devise.friendly_token.first(8)
    @user.password_confirmation = @user.password

    flash[:notice] = 'User created and invitation sent'
    if @user.save
      @user.send_reset_password_instructions
    else
      render 'edit'
    end
  end

  def create
    if @user.profile
      create_for_profile
      return
    end

    create! do |format|
      format.html do
        unless params[:redirect_location].blank?
          redirect_to params[:redirect_location]
        else
          redirect_to user_path(@user)
        end
      end
    end

  end

  def user_params
    if current_user.admin?
      params
      .require(:user)
      .permit([
        :email,
        :admin,
        :password,
        :password_confirmation,
        :profile_id,
        :profile_type
      ])
    else
      params
      .require(:user)
      .permit([
        :email,
        :password,
        :password_confirmation,
        :current_password
      ])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for resource do |f|
  = hidden_field_tag :redirect_location, params[:redirect_location]
  = f.input :profile_id, as: :hidden
  = f.input :profile_type, as: :hidden

  .row
    .col.s12
      .card.medium.z-depth-1
        .card-content
          .row
            = f.input :email, wrapper: :halve
            - if current_user.admin?
              .input-field.col.s12.m6
                = f.check_box :admin
                = f.label :admin
          .row
            = f.input :password, hint: !f.object.new_record?, input_html: { :autocomplete => "off" }, wrapper: :halve
            = f.input :password_confirmation, wrapper: :halve
            - unless can?(:manage, User)
              = f.input :current_password, required: true, wrapper: :halve

          .card-action
            = f.button :submit

app/views/users/_index.html.haml
.row
  .col.s12
    %ul.tabs
      %li.tab.col.s3
        = link_to 'New Experts', '#new-mentors'
      %li.tab.col.s3
        = link_to 'New Entrepreneurs', '#new-members'
      %li.tab.col.s3
        = link_to 'Never signed in', '#unconfirmed'
      %li.tab.col.s3
        = link_to 'All', '#all'

#new-mentors
  = render 'profile_list', collection: @mentors_with_no_user

#new-members
  = render 'profile_list', collection: @members_with_no_user

#unconfirmed
  = render 'list', collection: @unconfirmed

#all
  = render 'list', collection: @all

app/views/users/_profile.html.haml
%li.collection-item.avatar[profile]
  = image_tag profile.avatar_url, class: 'circle'
  .title= profile
  %p
    = t_model profile.class
    = "<%s>" % profile.email
  .secondary-content
    - if can?(:new, profile.class)
      .fixed-action-btn.horizontal
        = link_to create_for_profile_users_path(user: {profile_id: profile.id, profile_type: profile.class}), remote: true, method: :post, class: "btn-floating blue" do
          %i.large.material-icons add

app/views/users/_profile_list.html.haml
.list
  %ul.collection
    = render partial: 'profile', collection: collection

app/views/users/_user.html.haml
%li.collection-item.avatar
  - if user.profile
    = image_tag user.profile.avatar_url, class: 'circle'
  - else
    %i.material-icons.circle
      perm_identity
  .title= user
  - if user.profile
    %p
      = t_model user.profile.class
  .secondary-content
    - if can?(:edit, user) && 'users' == controller_name
      .fixed-action-btn.horizontal
        = link_to edit_user_path(user), class: "btn-floating btn-medium green" do
          %i.material-icons mode_edit

app/views/users/create_for_profile.js.erb
$('#<%= dom_id(@user.profile) %>').fadeOut()