config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      get :profile
      post :create_for_profile
    end
  end

  resources :team_mentors
  resources :team_members

  resources :members do
    resources :team_members
    resources :teams
  end
  resources :teams do
    resources :team_members do
      collection do
        get :new_form
      end
    end
    resources :team_mentors do
      collection do
        get :new_form
      end
    end
    resources :members
    resources :ratings, only: [:index]
    resources :mentorings
  end
  resources :mentors do
    resources :team_mentors
    resources :teams
    resources :ratings, except: :new
    resources :dashboard, only: :index
    resources :expert_sessions do
      member do
        post :book
      end
    end
  end

  resources :events do
    resources :attendances do
      member do
        post :attend
        post :decline
      end
    end
    collection do
      get :timeline
    end
  end
  resources :mentorings do
    resources :attendances do
      member do
        post :attend
        post :decline
      end
    end
    collection do
      get :timeline
    end
  end

  resources :expert_sessions do
    member do
      post :accept
      post :reject
    end
    resources :attendances
  end

  resources :attendances do
    member do
      post :attend
      post :decline
    end
  end

  resources :ratings, except: :new

  scope as: :calendar, path: 'calendar/:token' do
    controller :calendar do
      get :events
    end
  end

  root to: "users#profile"
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :mentor
  belongs_to :team
  has_many :ratings, dependent: :destroy

  has_many :attendances, dependent: :destroy

  validates_presence_of :summary, :start_at, :end_at

  default_scope -> { order(:start_at) }
  scope :passed, -> { where('start_at < ?', Time.zone.now)}
  scope :attended_by, -> (user) { joins(:attendances).where('attendances.state = ? AND attendances.guest_id = ?', Attendance.states['attending'], user.id) }
  scope :unrated, -> { joins('LEFT JOIN ratings ON events.id = ratings.event_id').where('ratings.event_id IS NULL') }
  scope :upcoming, -> { where('start_at >= ?', Date.today.beginning_of_day)}

  def to_s
    summary
  end

  def overdue?
    end_at.past?
  end

  # special event representing the current date
  def self.today
    Event.new(summary: 'Today',
              start_at: Date.today,
              end_at: Date.today)
  end

  # adds a today event to an array of events at the right position
  def self.add_today(events)
    events = events.to_a # decouple collection from AR to avoid updates
    events << Event.today
    return events.sort_by{ |e| e.start_at }
  end
end

app/controllers/events_controller.rb
class EventsController < CrudController
  def event_params
    permitted_params = params.require(:event)

    permitted_params.permit([
      :summary,
      :description,
      :start_at,
      :end_at,
      :location,
      :url
    ])
  end

  def update
    update! do |format|
      format.html do
        unless params[:redirect_location].blank?
          redirect_to params[:redirect_location]
        else
          redirect_to collection_url
        end
      end
    end
  end

  def timeline
    @events = Event.add_today(@events)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def colors(index)
    # The base color has no additional class
    colors = ['color-1', 'color-2', 'color-3', 'color-4']
    colors[index % colors.length]
  end

  def state_color(state)
    case state
    when 'invited'
      'grey lighten-2'
    when 'attending'
      'green'
    when 'declined'
      'red'
    end
  end

  def state_icon(state)
    case state
    when 'invited'
      'help'
    when 'attending'
      'event_available'
    when 'declined'
      'event_busy'
    end
  end

  # is the event in the past, today or in the future?
  def epoch_class(event)
    return 'today' if event.start_at.today?
    return 'past' if event.start_at < Date.today
    return 'future'
  end

  def duration_to_s(event)
    if event.start_at.to_date == event.end_at.to_date
      "%s %s - %s" % [
        event.start_at.strftime("%d.%m.%Y"),
        event.start_at.strftime("%H:%M"),
        event.end_at.strftime("%H:%M")
      ]
    else
      "%s - %s" % [
        event.start_at.strftime("%d.%m.%Y %H:%M"),
        event.end_at.strftime("%d.%m.%Y %H:%M")
      ]
    end
  end

  def duration_with_location_to_s(event)
    [duration_to_s(event), event.location.presence].compact.join(', ')
  end
end

app/views/events/_attendances_form.html.haml
- unless resource.new_record?
  .header
    %h4= t_model Attendance
    - if can? :create_attendance, resource
      %div(style="position: relative")
        .fixed-action-btn.horizontal(style="position: absolute")
          = link_to polymorphic_url([:new, resource, :attendance]), remote: true, class: "btn-floating btn-large blue" do
            %i.large.material-icons add

  %ul.collection.attendances
    = render resource.attendances

app/views/events/_event.html.haml
%li.collection-item.avatar
  %i.material-icons.circle today
  .title= event.summary
  %p
    = duration_with_location_to_s(event)
    %br
    = event.description

  .secondary-content
    - if can?(:edit, event)
      .fixed-action-btn.horizontal
        = link_to [:edit, event], class: "btn-floating btn-medium green" do
          %i.material-icons mode_edit

app/views/events/_form.html.haml
= simple_form_for resource, wrapper: :full do |f|
  .card.z-depth-1
    .card-content
      = render 'form_base', f: f

    .card-action
      = f.button :submit

  .section
    = render 'attendances_form'

app/views/events/_form_base.html.haml
.row
  = f.input :summary
  .datetime
    .input-field.col.s6.date
      = f.date_field :start_at, class: 'datepicker'
      = f.label :start_at, value: f.object.start_at&.to_s(:time), class: 'active'
    .input-field.col.s6.time
      = f.time_field :start_at, class: 'timepicker'
      = f.label :start_at, class: 'active'
    = f.hidden_field :start_at
  .datetime
    .input-field.col.s6.date
      = f.date_field :end_at, class: 'datepicker'
      = f.label :end_at, class: 'active'
    .input-field.col.s6.time
      = f.time_field :end_at, value: f.object.end_at&.to_s(:time), class: 'timepicker'
      = f.label :end_at, class: 'active'
    = f.hidden_field :end_at

  = f.input :location, wrapper: :halve
  = f.input :url, wrapper: :halve
  = f.input :description

app/views/events/index.haml
#events
  - @events.each_with_index do |event, index|
    / Add a paralax container if there is a new month
    - if event.start_at.strftime("%m") != @events[index - 1].start_at.strftime("%m")
      .parallax-container
        .parallax
          %img{src: image_path('picture2.jpg')}/

    .row
      / Month section if a new month
      .col.s4.m2.l2
        - if event.start_at.strftime("%m") != @events[index - 1].start_at.strftime("%m") || index == 0
          .month.left
            %h4= event.start_at.strftime("%b")
        - if event.start_at.strftime("%d%m") != @events[index - 1].start_at.strftime("%d%m")
          .day.left
            %a.btn-floating.btn-large.waves-effect.waves-light.light-green.date-circle{id: index}= event.start_at.strftime("%d")
        &nbsp

      / Add the event cards
      .col.s8.m10.l8.section.event
        .card.amber{class: colors(index)}
          .card-content.black-text
            %span.card-title= event.summary
            %p
              = event.description
            %p
              Starting at: <br><i class="fa fa-clock-o"></i> #{event.start_at.strftime("%H:%M") }  <i class="fa fa-calendar"></i> #{event.start_at.strftime("%d.%m") }
            %p
              Ending at:<br><i class="fa fa-clock-o"></i> #{event.end_at.strftime("%H:%M") } <i class="fa fa-calendar"></i> #{event.end_at.strftime("%d.%m") }
          .card-action
            %a.indigo-text{ href: edit_event_path(event)} Edit event

app/views/events/index.html.haml
.header
  %h2= t_title
  %div(style="position: relative")
    .fixed-action-btn.horizontal(style="position: absolute")
      = link_to '#calendar-modal', class: "btn-floating btn-large green modal-trigger" do
        %i.large.material-icons event
      = link_to url_for(action: :new), class: "btn-floating btn-large blue" do
        %i.large.material-icons add

= render 'list', collection: collection

#calendar-modal.modal
  .modal-content
    %h4= t('events.calendar.export')
    %div.collection
      = link_to "http://www.google.com/calendar/render?cid=#{CGI.escape calendar_events_url(current_user.calendar_token)}", class: 'collection-item', target: '_blank' do
        %i.material-icons event
        = t('events.calendar.add_to_google')
      = link_to calendar_events_url(current_user.calendar_token, protocol: 'webcal'), class: 'collection-item' do
        %i.material-icons open_in_browser
        = t('events.calendar.webcal')
      = link_to calendar_events_url(current_user.calendar_token), class: 'collection-item' do
        %i.material-icons file_download
        = t('events.calendar.download')
  .modal-footer
    = link_to t('crud.action.close'), '#', class: 'modal-action modal-close btn-flat waves-effect'

app/views/events/timeline.html.haml
#events


  - @events.each_with_index do |event, index|
    / Add a paralax container if there is a new month
    - if event.start_at.strftime("%m") != @events[index - 1].start_at.strftime("%m")
      .parallax-container
        .parallax
          = event.start_at.strftime("%B")
          %img{src: image_path("timeline_month.png")}/

    .row
      / Month section if a new month
      .col.s2.m2.l2
        - if event.start_at.strftime("%m") != @events[index - 1].start_at.strftime("%m") || index == 0
          .month.left{class: epoch_class(event) }
            %h4= event.start_at.strftime("%b")
        - if event.start_at.strftime("%d%m") != @events[index - 1].start_at.strftime("%d%m")
          .day.left{class: epoch_class(event), id: event.start_at.today? ? 'today' : nil}
            %a.btn-floating.btn-large{id: index}
              = event.start_at.strftime("%d")
        &nbsp;

      / Add the event cards
      .col.s10.event
        .card{class: colors(index)}
          .card-content.black-text
            %span.card-title= event.summary
            %p
              = event.description
            %p.datetime
              Starting at:&ensp;
              %span.time
                = event.start_at.to_s(:time)
              %span.date
                = event.start_at.strftime("%d.%m")
            %p.datetime
              Ending at:&emsp;
              %span.time
                = event.end_at.to_s(:time)
              %span.date
                = event.end_at.strftime("%d.%m")
          .card-action
            - if can?(:edit, event) && event.persisted?
              %a{ href: url_for([:edit, event])} Edit event
            .avatars
              - event.attendances.each_with_index do |a, i|
                = image_tag a.guest.avatar_url, class: ['circle', "attendance-state-#{a.state}"], style: "right: #{i*40}px"

  .fixed-action-btn.horizontal(style="position: fixed; z-index: 2;")
    = link_to new_event_path, class: "btn-floating btn-large blue" do
      %i.large.material-icons add