config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    collection do
      get :profile
      post :create_for_profile
    end
  end

  resources :team_mentors
  resources :team_members

  resources :members do
    resources :team_members
    resources :teams
  end
  resources :teams do
    resources :team_members do
      collection do
        get :new_form
      end
    end
    resources :team_mentors do
      collection do
        get :new_form
      end
    end
    resources :members
    resources :ratings, only: [:index]
    resources :mentorings
  end
  resources :mentors do
    resources :team_mentors
    resources :teams
    resources :ratings, except: :new
    resources :dashboard, only: :index
    resources :expert_sessions do
      member do
        post :book
      end
    end
  end

  resources :events do
    resources :attendances do
      member do
        post :attend
        post :decline
      end
    end
    collection do
      get :timeline
    end
  end
  resources :mentorings do
    resources :attendances do
      member do
        post :attend
        post :decline
      end
    end
    collection do
      get :timeline
    end
  end

  resources :expert_sessions do
    member do
      post :accept
      post :reject
    end
    resources :attendances
  end

  resources :attendances do
    member do
      post :attend
      post :decline
    end
  end

  resources :ratings, except: :new

  scope as: :calendar, path: 'calendar/:token' do
    controller :calendar do
      get :events
    end
  end

  root to: "users#profile"
end

app/models/mentor.rb
class Mentor < ActiveRecord::Base
  has_many :team_mentors, dependent: :destroy
  has_many :teams, through: :team_mentors, dependent: :restrict_with_error
  has_many :mentorings, dependent: :restrict_with_error
  has_many :expert_sessions, dependent: :restrict_with_error
  has_many :ratings, dependent: :destroy
  has_one  :user, as: :profile
  scope :with_no_user, -> {
    includes(:user).where(users: { id: nil })
  }

  include HasVcard

  mount_uploader :avatar, AvatarUploader

  include PgSearch
  pg_search_scope :by_text,
    using: { tsearch: { prefix: true } },
    against: [ :job_title, :who_i_am, :experience, :interests, :motivation ],
    associated_against: {
      vcard: HasVcardSupport.pg_search_against
    }

  # a mentor may be an lone expert or may have teams associated which makes him
  # to a real mentor
  def has_mentoring?
    0 < self.team_mentors_count
  end

  def to_s
    name
  end
end

app/controllers/mentors_controller.rb
class MentorsController < CrudController

  # apply default scope
  has_scope :vcard_default_scope, default: nil, allow_blank: true, unless: :by_text?, only: :index

  def edit
    upcoming_sessions = resource.expert_sessions.upcoming
    @fresh_expert_sessions = upcoming_sessions.fresh
    @unconfirmed_expert_sessions = upcoming_sessions.unconfirmed
    @confirmed_expert_sessions = upcoming_sessions.confirmed

    edit!
  end

  def show
    upcoming_sessions = resource.expert_sessions.upcoming
    @fresh_expert_sessions = upcoming_sessions.fresh
    @unconfirmed_expert_sessions = upcoming_sessions.unconfirmed
    @confirmed_expert_sessions = upcoming_sessions.confirmed

    show!
  end

  def mentor_params
    permitted_params = params.require(:mentor)

    permitted_params.permit([
      :job_title,
      :who_i_am,
      :experience,
      :interests,
      :motivation,
      :avatar,
      HasVcardSupport.permitted_params
    ])
  end

  def create
    create! do |format|
      format.html

      format.js do
        resource.team_mentors.create(team_id: params[:team_id]) if params[:team_id].present?
      end
    end
  end
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/views/mentors/_expert_sessions.html.haml
#expert-sessions
  .unconfirmed.section
    %h4= 'Waiting for Your Answer'
    = render 'expert_sessions/list', collection: @unconfirmed_expert_sessions, resource_class: ExpertSession

  .confirmed.section
    %h4= 'Confirmed'
    = render 'expert_sessions/list', collection: @confirmed_expert_sessions, resource_class: ExpertSession

  .fresh.section
    %h4= 'New/No pending Requests'
    %div(style="position: relative")
      .fixed-action-btn.horizontal(style="position: absolute")
        = link_to new_mentor_expert_session_path(resource), remote: true, class: "btn-floating btn-medium blue" do
          %i.large.material-icons add

    = render 'expert_sessions/list', collection: @fresh_expert_sessions, resource_class: ExpertSession

app/views/mentors/_form.html.haml
.row
  .col.s12
    %ul.tabs
      %li.tab.col.s3
        = link_to 'Profile', '#profile'
      - if resource.persisted?
        %li.tab.col.s3
          = link_to 'Expert Sessions', '#expert-sessions'
      - if resource.has_mentoring?
        %li.tab.col.s3
          = link_to 'Mentoring', '#mentoring'
      - if resource.user
        %li.tab.col.s3
          = link_to 'Account', '#user'

#profile
  = simple_form_for resource do |f|
    - if defined?(team_id) && team_id.present?
      = hidden_field_tag :team_id, team_id

    .row
      .col.s12.m4
        .card.medium.z-depth-1
          .card-image.full
            %img{name: 'mentor[avatar]', alt: "no avatar uploaded yet", src: resource.avatar.url }/
          .card-action
            = f.input :avatar, as: :image_preview, label: 'upload avatar', label_html: { class: 'waves-effect waves-light btn waves-input-wrapper' }

      .col.s12.m8
        .card.z-depth-1
          .card-content
            %span.card-title Personal information
            = render 'vcards/form', f: f
          .card-action
            = f.button :submit

      .col.s12
        .card.z-depth-1
          .card-content
            .row= f.input :job_title, wrapper_class: 'col s12'
            .row= f.input :who_i_am, wrapper_class: 'col s12'
            .row= f.input :experience, wrapper_class: 'col s12'
            .row= f.input :interests, wrapper_class: 'col s12'
            .row= f.input :motivation, wrapper_class: 'col s12'
          .card-action
            = f.button :submit

- if resource.persisted?
  = render 'expert_sessions'

- if resource.has_mentoring?
  #mentoring
    .section
      %h4= t_title(:index, Mentoring)
      %div(style="position: relative")
        .fixed-action-btn.horizontal(style="position: absolute")
          = link_to new_team_mentoring_path(resource), remote: true, class: "btn-floating btn-medium blue" do
            %i.large.material-icons add
      = render 'list', collection: resource.mentorings.upcoming, resource_class: Mentoring

    .section_divider
    .section
      %h4= t_title(:index, Team)
      = render 'list', collection: resource.teams, resource_class: Team

- if resource.user
  #user
    = render 'users/form', resource: resource.user

app/views/mentors/_index.html.haml
.index{class: resource_class&.name&.tableize}
  - if resource_class.respond_to?(:by_text)
    = render 'list_search'

  .list
    = guarded_paginate collection
    .row
      = render collection
    = guarded_paginate collection

app/views/mentors/_mentor.html.haml
.col.s12.m6.l4
  .card.large.z-depth-2
    .card-image.waves-effect.waves-block.waves-light
      - if mentor.avatar_url
        = image_tag mentor.avatar_url, class: :activator
      - else
        %i.material-icons.img-placeholder person_outline
    .card-content
      %span.card-title.activator
        = mentor
      .divider
      %p
        = mentor.job_title
      %p
        = mentor.who_i_am
      %p
        = mentor.interests
    .card-action
      %i.material-icons.activator.right more_vert
      = link_to 'edit', edit_mentor_path(mentor) if can? :edit, mentor
      .activator
        = "%s open Expert Sessions" % [ mentor.expert_sessions.bookable.count ]
    .card-reveal
      %span.card-title.grey-text.text-darken-4
        =mentor
        %i.material-icons.right close

      .row
        .col.s12.field
          .label Open Expert Sessions
          %ul.value
            - mentor.expert_sessions.each do |session|
              %li= link_to duration_to_s(session), [:book, mentor, session], remote: true, method: :post if can? :book, session
      .row
        .col.s12.field
          .label=Mentor.human_attribute_name(:job_title)
          .value=mentor.job_title
      .row
        .col.s12.field
          .label=Mentor.human_attribute_name(:who_i_am)
          .value=mentor.who_i_am
      .row
        .col.s12.field
          .label=Mentor.human_attribute_name(:interests)
          .value=mentor.interests
      .row
        .col.s12.field
          .label=Mentor.human_attribute_name(:motivation)
          .value=mentor.motivation

app/views/mentors/create.js.erb
<%= render 'create' %>

$('.collection.mentors').html('<%=j render "list", resource_class: Mentor, collection: resource.teams.first.mentors %>')

init();